camunda.bpm.admin-user:
  id: demo
  password: demo
spring:
  kafka:
    bootstrap-servers: 172.25.43.101:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          deserializer:
            value:
              delegate:
                class: com.example.workflow.deserializer.HistoryEventDeserializer
  datasource:
    url: jdbc:h2:file:./camunda-h2-database
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8081
logging:
  level:
    root: info